import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "../components/student/sidebar";
import "@/public/icons/app.css";
import Navbar from "../components/student/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Student Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex bg-gray-100">
      <div className="fixed top-0 left-0 right-0 z-20">
        <Navbar />
      </div>

      <Sidebar />
      <div className="flex-grow p-6 mt-[2rem]">{children}</div>
    </div>
  );
}
