import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Sidebar from "../components/sidebar";
import Navbar from "../components/navbar";
import NavbarTeacher from "../components/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
        {/* Fixed Navbar at the top */}
        <div className="fixed top-0 left-0 right-0 z-20">
          <NavbarTeacher />
        </div>

        {/* Content area with sidebar and main content */}
        <div className="flex bg-gray-100 min-h-screen pt-16">
          {/* Sidebar will handle its own state and positioning */}
          <Sidebar />

          {/* Main content area - transitions with sidebar state */}
          <div
            id="main-content"
            className="flex-grow p-4 transition-all duration-300"
          >
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
